"""Reminder and proactive Notification models."""

import enum
from sqlalchemy import Boolean, Column, DateTime, Enum, String, Text
from sqlalchemy.orm import relationship

from app.database.base import Base, TenantMixin, TimestampMixin, UUIDPrimaryKeyMixin


class ReminderSource(str, enum.Enum):
    """Source of reminder creation."""
    ROBOT_VOICE = "ROBOT_VOICE"
    APP_MANUAL = "APP_MANUAL"


class NotificationCategory(str, enum.Enum):
    """Categories for proactive business alerts."""
    LOW_STOCK = "LOW_STOCK"
    PAYMENT_DUE = "PAYMENT_DUE"
    HARDWARE_OFFLINE = "HARDWARE_OFFLINE"
    SYSTEM = "SYSTEM"


class Reminder(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """Operational reminders created by owner voice or mobile app."""
    __tablename__ = "reminders"

    title = Column(String(200), nullable=False)
    due_datetime = Column(DateTime(timezone=True), nullable=False)
    is_recurring = Column(Boolean, nullable=False, default=False)
    recurrence_rule = Column(String(100), nullable=True)
    is_completed = Column(Boolean, nullable=False, default=False)
    source = Column(Enum(ReminderSource), nullable=False, default=ReminderSource.ROBOT_VOICE)

    # Relationships
    business = relationship("Business", back_populates="reminders")


class Notification(Base, UUIDPrimaryKeyMixin, TenantMixin, TimestampMixin):
    """Proactive alerts generated by the automation/manager engine."""
    __tablename__ = "notifications"

    title = Column(String(150), nullable=False)
    message = Column(Text, nullable=False)
    category = Column(Enum(NotificationCategory), nullable=False, default=NotificationCategory.SYSTEM)
    is_read = Column(Boolean, nullable=False, default=False)

    # Relationships
    business = relationship("Business", back_populates="notifications")
