"""Persistent Task Job and Result models for asynchronous background operations."""

from datetime import datetime, timezone
import enum
import json
from typing import Any, Dict, Optional
import uuid

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database.base import Base, TimestampMixin


class JobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskJob(Base, TimestampMixin):
    """
    Persistent record of a long-running background task (e.g., Weekly Strategy, Sales Report).
    Uses human-readable task identifiers such as TASK-101.
    """
    __tablename__ = "task_jobs"

    id = Column(String(64), primary_key=True, index=True)
    business_id = Column(UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"), nullable=True, index=True)
    type = Column(String(64), nullable=False, index=True)
    status = Column(String(32), nullable=False, default=JobStatus.QUEUED.value, index=True)
    progress = Column(Integer, nullable=False, default=0)
    current_step = Column(String(128), nullable=False, default="queued")
    result_id = Column(String(64), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    error_message = Column(Text, nullable=True)

    # Relationships
    results = relationship("TaskJobResult", back_populates="task", cascade="all, delete-orphan")
    events = relationship("TaskJobEvent", back_populates="task", cascade="all, delete-orphan")


class TaskJobResult(Base, TimestampMixin):
    """Structured JSON result generated by a completed background task."""
    __tablename__ = "task_job_results"

    id = Column(String(64), primary_key=True, default=lambda: f"RES-{uuid.uuid4().hex[:8].upper()}")
    task_id = Column(String(64), ForeignKey("task_jobs.id", ondelete="CASCADE"), nullable=False, index=True)
    result_type = Column(String(64), nullable=False)
    result_json_raw = Column(Text, nullable=False, default="{}")

    task = relationship("TaskJob", back_populates="results")

    @property
    def result_json(self) -> Dict[str, Any]:
        try:
            return json.loads(self.result_json_raw or "{}")
        except Exception:
            return {}

    @result_json.setter
    def result_json(self, value: Dict[str, Any]):
        self.result_json_raw = json.dumps(value or {})


class TaskJobEvent(Base):
    """Audit event tracking lifecycle transitions and milestones of background tasks."""
    __tablename__ = "task_job_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    task_id = Column(String(64), ForeignKey("task_jobs.id", ondelete="CASCADE"), nullable=False, index=True)
    event_type = Column(String(64), nullable=False)
    payload_raw = Column(Text, nullable=False, default="{}")
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
    )

    task = relationship("TaskJob", back_populates="events")

    @property
    def payload(self) -> Dict[str, Any]:
        try:
            return json.loads(self.payload_raw or "{}")
        except Exception:
            return {}

    @payload.setter
    def payload(self, value: Dict[str, Any]):
        self.payload_raw = json.dumps(value or {})
